import {
  LayoutDashboard,
  FileText,
  Image,
  Settings,
  User,
  Menu,
  X,
  LogOut,
  Bell,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  Download,
  Upload,
  Filter,
} from "lucide-react";

export const Icons = {
  Dashboard: LayoutDashboard,
  Blog: FileText,
  Media: Image,
  Settings: Settings,
  Profile: User,
  Menu: Menu,
  Close: X,
  Logout: LogOut,
  Bell: Bell,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Search: Search,
  Plus: Plus,
  Edit: Edit,
  Trash: Trash2,
  Eye: Eye,
  Download: Download,
  Upload: Upload,
  Filter: Filter,
};
